version: 2.1
jobs:
  # build:
  # for npm install and testing --> job macos-build will require build
  #
  android-build:
    working_directory: ~/gatgu-client
    docker:
      - image: circleci/android:api-29
    # environement
    steps:
      - checkout
      - run: 
          command: npm install
          working_directory: ~/gatgu-client
      - run: 
          command: |
            cd ~/Library/Android/sdk/tools/bin/
            ./sdkmanager --licenses
      - run:
          command: npm run android
          working_directory: android
  # macos-build:
  #   working_directory: ~/gatgu-client
  #   macos:
  #     xcode: 11.3.0
  #   # environement
  #   steps:
  #     - checkout
  #     - run: npm install
  #     - run:
  #         command: pod install
  #         working_directory: ios
  #     - run:
  #         command: npm run ios
  #         working_directory: ios

workflows:
  macos:
    jobs:
      - android-build