export enum WSMessage {
  ENTER_ROOM = 'ENTER',
  ENTER_ROOM_SUCCESS = 'ENTER_SUCCESS',
  ENTER_ROOM_FAILURE = 'ENTER_FAILURE',
  SEND_MESSAGE = 'MESSAGE',
  RECEIVE_MESSAGE_SUCCESS = 'MESSAGE_SUCCESS',
  RECEIVE_MESSAGE_FAILURE = 'MESSAGE_FAILURE',
  RECEIVE_UPDATED_STATUS = 'UPDATE_STATUS',
  EXIT_ROOM = 'EXIT',
  EXIT_ROOM_SUCCESS = 'EXIT_SUCCESS',
  EXIT_ROOM_FAILURE = 'EXIT_FAILURE',
}
